# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-5.1

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/j-mueller/virtual-hom
    commit: 800aca3bb54078b8237a2a3bfe004922cd3a0761

# Extra package databases containing global packages
extra-package-dbs: []

compiler: ghcjs-0.2.0.20160315_ghc-7.10.2
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20160315_ghc-7.10.2:
    url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20160315/ghcjs-0.2.0.20160315.tar.gz"